### ISSUE TITLE
applying hiearchy twice creates unneccessary database columns

### ISSUE THREAD

**Issue by briceburg** [micschk/silverstripe-excludechildren#8]
I noticed that when applying ExcludeChildren , that an additional ParentID field is created on the basetable of the extended object. E.g. If I extend PracticeSection with ExcludeChildren, I get;
```
Field PracticeSection.ParentID: created as int(11) not null default 0
Index PracticeSection.ParentID: created as ("ParentID")
Field PracticeSection_Live.ParentID: created as int(11) not null default 0
Index PracticeSection_Live.ParentID: created as ("ParentID")
Field PracticeSection_versions.ParentID: created as int(11) not null default 0
Index PracticeSection_versions.ParentID: created as ("ParentID")
```

I assume this has to do with applying Hiearchy twice, and it smells like an inefficiency...   Do you think it is required?  I can help track it down if you think it's worth correctling. Let me know.

**Comment by micschk** [comment]
@briceburg Thanks for noticing, I've updated the module today to extend DataobjectExtension instead of Hierarchy, this fixes the ParentID issue. Had to duplicate some code from Hierarchy though, but that should be fine.

**Comment by briceburg** [comment]
@micschk looks good! Thanks for checking into this. Keeping the code in sync w/ Hiearchy is probably easy to do -- but, providing no code changes were made to a function, did you try; 

```php
$this->owner->FunctionFromHiearchy()
```

? May make maintenance easier going forward.
